time-off/app/config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :time_off_requests, only: [:index, :new, :create, :show]

  get '/manager/time_off_requests', to: 'time_off_requests#manager_index', as: 'manager_time_off_requests'
  patch '/manager/time_off_requests/:id/approve', to: 'time_off_requests#approve', as: 'approve_time_off_request'
  patch '/manager/time_off_requests/:id/deny',    to: 'time_off_requests#deny',    as: 'deny_time_off_request'

  resources :employees
  resources :departments
  resources :documents, only: [] do
    member do
      get :download
    end
  end
  

end

time-off/app/app/views/layouts/application.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <title>Time Off Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to "Dashboard", root_path %> |
        <%= link_to "My Requests", time_off_requests_path %> |
        <% if current_user&.role == 'manager' || current_user&.role == 'admin' %>
          <%= link_to "All Requests", manager_time_off_requests_path %> |
        <% end %>
        <%= link_to "Employees", employees_path %> |
        <%= link_to "Departments", departments_path %> |
        <%= link_to "Logout", logout_path, method: :delete %>
      </nav>
    </header>

    <% if flash[:notice] %>
      <p class="flash-notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="flash-alert"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>

    <footer>
      <small>&copy; <%= Time.now.year %> Time Off Management</small>
    </footer>
  </body>
</html>