time-off/app/config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :time_off_requests, only: [:index, :new, :create, :show]

  get '/manager/time_off_requests', to: 'time_off_requests#manager_index', as: 'manager_time_off_requests'
  patch '/manager/time_off_requests/:id/approve', to: 'time_off_requests#approve', as: 'approve_time_off_request'
  patch '/manager/time_off_requests/:id/deny',    to: 'time_off_requests#deny',    as: 'deny_time_off_request'

  resources :employees
  resources :departments
  resources :documents, only: [] do
    member do
      get :download
    end
  end
  

end

time-off/app/app/models/employee.rb
# app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_many :time_off_requests, dependent: :destroy
  has_many :managed_departments, class_name: 'Department', foreign_key: 'manager_id'

  validates :first_name, :last_name, :title, presence: true
end

time-off/app/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :require_login
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:notice] = "Employee created successfully"
      redirect_to employees_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      flash[:notice] = "Employee updated"
      redirect_to employees_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @employee.destroy
    flash[:notice] = "Employee deleted"
    redirect_to employees_path
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :title, :department_id)
  end
end

time-off/app/app/views/employees/index.html.erb
<!-- app/views/employees/index.html.erb -->
<h1>All Employees</h1>

<% if @employees.present? %>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Title</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.id %></td>
          <td><%= employee.first_name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.title %></td>
          <td>
            <%= link_to "Show", employee_path(employee) %> |
            <%= link_to "Edit", edit_employee_path(employee) %> |
            <%= link_to "Delete", employee_path(employee), method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No employees found.</p>
<% end %>